export const APP = {
  name: "Northwind AI",
  name2: "Northstar Analytics",
  nameShort: "NorthwindAI",
  nameShort2: "Northstar",
  slug: "northwind-ai",
  slug2: "northstar-analytics",
  //
  title: "AI Automation Web Services",
  title2: "Discover Web3 Apps",
  titleVerbose: "Northwind AI - AI Automation Web Services",
  titleVerbose2: "Northstar Analytics | Discover Web3 Apps",
  keywords: "northwind ai, northwind db, ai automation, ai agents",
  description:
    "Transform repetitive business processes into smart, autonomous AI agents. Automate virtual workflows and Point-of-Sale (POS) systems with Northwind AI.",
  description2:
    "Discover community-led Web3 projects powered by Bitcoin Verse Ecosystem, and Northstar Analytics",
  owner: "HWP Labs",
  creator: "Emmanuel Tugbeh",
  startData: "2026-01-30T20:12:35.000",
  launchData: "2026-02-14T09:00:00.000",
  //
  domain: "northwindai.org",
  domain2: "Qverse.store",
  website: "https://northwindai.org",
  socialPreview: "https://northwindai.org/social-preview.png",
  email: "no-reply@northwindai.org",
  ccEmail: "etugbeh@outlook.com",
  bccEmail: "tugbeh.osaretin@gmail.com",
  tel: "+2348169960927",
  telDisplayText: "(+234)81 6996 0927",
  whatsappSalesUrl: "https://wa.me/2348169960927",
  whatsappGroupUrl: "https://chat.whatsapp.com/Id9WYTRrbxAHcTUfr3F5jv",
  repositoryName: "hwp-labs/northwind-ai-app",
  repositoryUrl: "https://github.com/hwp-labs/northwind-ai-app",
  repositoryApiName: "hwp-labs/northwind-ai",
  repositoryApiUrl: "https://github.com/hwp-labs/northwind-ai",
  //
  colors: {
    white: "#edf1f2",
    black: "#120e0d",
    brand: "#0092dd",
    contrast: "#dd4a00",
    bot: "#90c9ca",
    fuchsia: "#D946EF",
    opayGreen: "#1dcf9f",
    opayBlue: "#200f5f",
    info: "oklch(0.488 0.243 264.376)",
    success: "oklch(0.696 0.17 162.48)",
    warning: "oklch(0.769 0.188 70.08)",
    danger: "oklch(0.645 0.246 16.439)",
  },
} as const;
