import { EpisodeDto } from "./types";

export const data: EpisodeDto[] = [
  {
    id: 12,
    datetime: "2026-06-03T19:00:00.000Z",
    thumbnail: "/uploads/logos/nvidia.png",
    topic: "Redefining Jobs' Purpose in the Age of AI",
    summary:
      "Keynotes from Madison Huang's speech at Seoul National University (https://youtu.be/dhMPSzedWNQ)",
    tags: ["X-Ray", "ECG", "Urinalysis", "Django"],
    spaceUrl: "#https://x.com/i/spaces/1RKZzzBwanMKB",
    listeners: 0,
    liveListeners: 0,
    series: "cs",
  },
  {
    id: 11,
    datetime: "2026-05-30T19:00:00.000Z",
    thumbnail: "/uploads/logos/ubth.png",
    topic: "Routine Medical Investigations_ API Modeling",
    topicShort: "Routine Investigations API Modeling",
    tags: ["X-Ray", "ECG", "Urinalysis", "Django"],
    guests: [14],
    notionUrl:
      "https://held-gambler-004.notion.site/Routine-Investigations-Modeling-36c6a7cc633c8017b911d6266fa82422",
    spaceUrl: "https://x.com/i/spaces/1RKZzzBwanMKB",
    listeners: 66,
    liveListeners: 58,
    series: "fc",
  },
  {
    id: 10,
    datetime: "2026-05-28T19:00:00.000Z",
    thumbnail: "/uploads/logos/siiqo.png",
    topic: "Siiqo Design Session",
    summary: "Escrow-based, Crypto-enabled, Digital Storefront for SMEs",
    tags: ["Marketplace", "Escrow", "Stablecoin", "#Invoicing"],
    guests: [12, 13],
    notionUrl:
      "https://held-gambler-004.notion.site/Siiqo-36c6a7cc633c8132842bf67ada4dd93d",
    spaceUrl: "https://x.com/i/spaces/1qGvvvewvbkGB",
    listeners: 67,
    liveListeners: 42,
  },
  {
    id: 9,
    datetime: "2026-05-17T19:00:00.000Z",
    thumbnail: "/uploads/logos/moniepoint.png",
    topic: "KPIs of World-Class Software Engineers",
    summary:
      "Keynotes from Tosin Eniolorunda's speech at The Platform Nigeria (https://youtu.be/OeP5Rs96OGY)",
    tags: ["Ownership", "Mentorship", "Scalability"],
    guests: [11, 10],
    notionUrl:
      "https://held-gambler-004.notion.site/KPIs-of-World-Class-Engineers-3486a7cc633c8078980ded890c2c9cc6",
    spaceUrl: "https://x.com/i/spaces/1mGPaLAgERYJN",
    listeners: 24,
    liveListeners: 14,
    series: "fc",
  },
  {
    id: 8,
    datetime: "2026-04-18T19:00:00.000Z",
    thumbnail: "/uploads/logos/verse.png",
    topic: "Hype To Adoption: Building Web3 Products",
    _notes: "Hosted on Verse Radio (@realVerseRadio)",
    guests: [9, 8, 7],
    displayAvatars: [
      "/images/icon-hwp.png",
      "/uploads/logos/btc.png",
      "/uploads/logos/verse.png",
    ],
    spaceUrl: "#",
    listeners: 243,
    liveListeners: 243,
    series: "fc",
  },
  {
    id: 7,
    datetime: "2026-04-12T19:00:00.000Z",
    thumbnail: "/uploads/logos/grab.png",
    topic: "Grab.com from MVP to Product Market Fit",
    summary:
      "Keynotes from Anthony Tan's interview by CNBC Int'l (https://youtu.be/PR2194ddosg)",
    _notes: { username: "@InsideGrab" },
    notionUrl:
      "https://held-gambler-004.notion.site/Grab-com-from-MVP-to-PMF-3406a7cc633c817aba03ed635c6f6253",
    spaceUrl: "https://x.com/i/spaces/1YxNrZNPNnpxw",
    listeners: 33,
    liveListeners: 10,
    series: "cs",
  },
  {
    id: 6,
    datetime: "2026-04-05T19:00:00.000Z",
    thumbnail: "/uploads/logos/adiz.png",
    topic: "Brand-Led Growth Hacking",
    summary:
      "Designing a brand identity that drive sales and customer loyalty.",
    guests: [6],
    notionUrl:
      "https://held-gambler-004.notion.site/Brand-Led-Growth-Hacking-3336a7cc633c810692e6e80f80946edb",
    spaceUrl: "https://x.com/i/spaces/1rGmqojWqzqGy",
    listeners: 45,
    liveListeners: 31,
    series: "fc",
  },
  {
    id: 5,
    datetime: "2026-03-29T19:00:00.000Z",
    thumbnail: "/uploads/logos/tetra.png",
    topic: "Tetra Design Session",
    summary: "Virtual Dollar Cards for seamless Int'l transactions.",
    guests: [5],
    notionUrl:
      "https://held-gambler-004.notion.site/Tetra-3316a7cc633c81429fabfb80a8601f8d",
    spaceUrl: "https://x.com/i/spaces/1nxeLyZOkXLJX",
    listeners: 41,
    liveListeners: 21,
  },
  {
    id: 4,
    datetime: "2026-03-22T19:00:00.000Z",
    thumbnail: "/uploads/logos/izivote.png",
    topic: "Izivote Design Session",
    summary: "Cloud-based voting platform for events and campaigns.",
    guests: [4],
    notionUrl:
      "https://held-gambler-004.notion.site/Izivote-3206a7cc633c807dbd55c6fbb373ff37",
    spaceUrl: "https://x.com/i/spaces/1XGygmPjeMkxM",
    listeners: 92,
    liveListeners: 33,
  },
  {
    id: 3,
    datetime: "2026-03-15T19:00:00.000Z",
    thumbnail: "/uploads/logos/bookin.png",
    topic: "Bookin Design Session",
    summary: "All-in-one booking platform for creative professionals",
    guests: [3],
    notionUrl:
      "https://held-gambler-004.notion.site/Bookin-3226a7cc633c81f1a9d8ebbce7bbc6b3",
    spaceUrl: "https://x.com/i/spaces/1DxleEjawjlKL",
    listeners: 136,
    liveListeners: 112,
  },
  {
    id: 2,
    datetime: "2026-03-08T19:00:00.000Z",
    thumbnail: "/uploads/logos/scupex.png",
    topic: "Scupex Design Session",
    summary: "Cloud-native, Multi-tenant School Management Solution",
    guests: [2],
    notionUrl:
      "https://held-gambler-004.notion.site/Scupex-31b6a7cc633c81eba6adcdddbe8fa5a1",
    spaceUrl: "https://x.com/i/spaces/1qGvvkLwDBAGB",
    listeners: 139,
    liveListeners: 103,
  },
  {
    id: 1,
    datetime: "2026-03-01T19:00:00.000Z",
    topic: "Northstar Design Session",
    summary: "AI-native, Cross-platform Product Analytics Solution",
    notionUrl:
      "https://held-gambler-004.notion.site/Northwind-AI-31b6a7cc633c8075b78ef30bf30c7ec7",
    spaceUrl: "#",
    listeners: 31,
    liveListeners: 18,
  },
];
