import { EpisodeDto } from "./types";

export const data: EpisodeDto[] = [
  {
    id: 26,
    datetime: "2026-07-26T19:00:00.000Z",
    thumbnail: "/uploads/logos/binx.jpg",
    topic: "Binx AI Design Session",
    topicRichText: "Binx AI<br/>Design Session",
    tags: ["AI Chat", "Image Generation", "Voice Transcription"],
    guests: [22, 23],
    virtualLink: "#",
    virtualPlatform: "yt",
    listeners: 0,
    liveListeners: 0,
    meta: {
      src: "/uploads/logos/binx.jpg",
      title:
        "WhatsApp AI Agent & Assistant | Web Search | Image Generation & More",
      url: "usebinx.com",
      cta: "Get Started",
    },
  },
  {
    id: 25,
    datetime: "2026-07-23T20:00:00.000Z",
    thumbnail: "/uploads/logos/uniben.png",
    topic: "MSC CSC 19/20 - Leveraging AI & ML",
    topicRichText: "MSC CSC <span>19/20</span><br/>Virtual Reunion",
    tags: ["Leveraging AI", "Prediction", "Decision Making"],
    virtualLink: "https://x.com/i/spaces/1nJOLLZqBykxR",
    listeners: 0,
    liveListeners: 0,
    series: "fc",
  },
  {
    id: 24,
    datetime: "2026-07-19T19:00:00.000Z",
    thumbnail: "/uploads/logos/edusphere.png",
    topic: "Smart EduSphere Design Session",
    tags: ["AI-Native", "Multi-Tenant", "OIDC Secure"],
    guests: [21],
    virtualLink: "https://x.com/i/spaces/1dKrPPVvdbqJX",
    listeners: 4,
    liveListeners: 3,
    meta: {
      src: "/uploads/logos/edusphere.png",
      title:
        "All-In-One School Management OS. Admissions, Bursary, CBT Exams, Rep...",
      url: "vicomeg.com",
      cta: "Register Now",
    },
  },
  {
    id: 23,
    datetime: "2026-07-12T19:00:00.000Z",
    thumbnail: "/uploads/logos/thesinova.png",
    topic: "Empirical Analysis & Decision Making",
    tags: ["Inference", "Classification", "Forecast"],
    guests: [20],
    virtualLink: "https://x.com/i/spaces/1yGBeeAYNgMKN",
    listeners: 4,
    liveListeners: 2,
    series: "fc",
    meta: {
      src: "/uploads/logos/thesinova.png",
      title:
        "High-performance Solutions at the Intersection of Academia & Techno...",
      url: "thesinova.com",
      cta: "Contact Us",
    },
  },
  {
    id: 22,
    datetime: "2026-07-08T09:00:00.000Z",
    thumbnail: "/uploads/logos/oau.jpg",
    topic: "Event-Driven Programming Pt.2",
    summary:
      "A Virtual Guest Lecture + Vibe Coding Session at the Dept. of Software Engineering, OAU",
    tags: ["Control Flow", "BOM & DOM", "async/await"],
    virtualLink: "https://youtu.be/N8ZCWAtmcF8",
    virtualPlatform: "yt",
    listeners: 100,
    liveListeners: 30,
    series: "fc",
    meta: {
      src: "/uploads/logos/oau.jpg",
      title:
        "SEN106/SEN216 - Introduction to Web Technology | Obafemi Awolowo Uni...",
      url: "oauife.edu.ng",
      cta: "Watch Now",
    },
  },
  {
    id: 21,
    datetime: "2026-07-05T19:00:00.000Z",
    thumbnail: "/uploads/logos/lani.png",
    topic: "LANI App Design Session",
    tags: ["Order", "Sell", "Deliver"],
    guests: [19],
    virtualLink: "https://x.com/i/spaces/1dGYllAbQAoKX",
    listeners: 11,
    liveListeners: 9,
    meta: {
      src: "/uploads/logos/lani.png",
      title:
        "Lani | Order, Sell & Deliver. All In One Platform. Meals & Essentials Services.",
      url: "lani.ng",
      cta: "Download Now",
    },
    _notes: {
      user: "https://play.google.com/store/apps/details?id=com.savic3916.lanieats",
      merchant:
        "https://play.google.com/store/apps/details?id=com.lanieats.merchants",
      rider: "https://play.google.com/store/apps/details?id=com.lanieats.rider",
    },
  },
  {
    id: 20,
    datetime: "2026-07-01T09:00:00.000Z",
    thumbnail: "/uploads/logos/oau.jpg",
    topic: "Event-Driven Programming Pt.1",
    summary:
      "A Virtual Guest Lecture at the Department of Computer Science & Engineering, OAU",
    tags: ["Control Flow", "BOM & DOM", "async/await"],
    virtualLink: "https://youtu.be/cGoyAmGwDog",
    virtualPlatform: "yt",
    listeners: 147,
    liveListeners: 60,
    series: "fc",
    meta: {
      src: "/uploads/logos/oau.jpg",
      title:
        "SEN106/SEN216 - Introduction to Web Technology | Obafemi Awolowo Uni...",
      url: "oauife.edu.ng",
      cta: "Watch Now",
    },
  },
  {
    id: 19,
    datetime: "2026-06-28T19:00:00.000Z",
    thumbnail: "/uploads/logos/npower.jpg",
    topic: "SOW: Government Subcontractors",
    tags: ["Scope", "Deliverables", "Constraints"],
    guests: [17, 18],
    virtualLink: "https://x.com/i/spaces/1wGWjjElmNNKQ",
    listeners: 17,
    liveListeners: 17,
    series: "fc",
    meta: {
      src: "/uploads/logos/inec.png",
      title:
        "Continuous Voter Registration - INEC Independent National Electorial Com...",
      url: "cvr.inecnigeria.org",
      cta: "Register Now",
    },
  },
  {
    id: 18,
    datetime: "2026-06-26T19:00:00.000Z",
    topic: "Study of Pragmatics & Cryptography",
    tags: ["Anagram", "Pangram", "Palindrome"],
    guests: [16],
    virtualLink: "https://x.com/i/spaces/1pKkOOEXPnXKj",
    listeners: 8,
    liveListeners: 6,
    series: "fc",
  },
  {
    id: 17,
    datetime: "2026-06-21T19:00:00.000Z",
    thumbnail: "/uploads/logos/siiqo.png",
    topic: "Comms Strategy for Startups",
    tags: ["Clarity", "Alignment ", "Tone"],
    guests: [10],
    virtualLink: "https://x.com/i/spaces/1DGleemXPqzJL",
    listeners: 22,
    liveListeners: 21,
    series: "fc",
    meta: {
      src: "/uploads/logos/siiqo.png",
      title: "Escrow-based, Crypto-enabled, Digital Storefront for SMEs",
      url: "siiqo.com",
      cta: "Get Started",
    },
  },
  {
    id: 16,
    datetime: "2026-06-19T19:00:00.000Z",
    thumbnail: "/uploads/logos/awore.png",
    topic: "ACID Traits for Agile Workflows",
    tags: ["PRD", "Sprints", "Time Estimates"],
    guests: [15],
    virtualLink: "https://x.com/i/spaces/1yxBeeBWbpWJN",
    listeners: 7,
    liveListeners: 6,
    series: "fc",
    meta: {
      src: "/uploads/logos/awore.png",
      title: "Handcrafted Textile Brand Creating Intentional Àdìrẹ Fabrics",
      url: "awo_oore",
      cta: "Contact Us",
      social: "ig",
    },
  },
  {
    id: 15,
    datetime: "2026-06-14T20:00:00.000Z",
    thumbnail: "/uploads/logos/tan.png",
    topic: "Youth Politics & Voter Pre-Registration Data",
    tags: ["Democratic", "Progressive", "Transparent"],
    guests: [14],
    virtualLink: "https://x.com/i/spaces/1pKdRRAwWWNJW",
    listeners: 10,
    liveListeners: 8,
    series: "fc",
    meta: {
      src: "/uploads/logos/tan.png",
      title: "Independent, Community-Driven Social & Economic Empowerme...",
      url: "tribeallianceng",
      cta: "Get Involved",
      social: "fb",
    },
  },
  {
    id: 14,
    datetime: "2026-06-12T19:00:00.000Z",
    thumbnail: "/uploads/logos/distrokid.jpg",
    topic: "Gospel Music & Lossless Audio Compression",
    _notes: {
      url: "https://distrokid.com/hyperfollow/jamiahgodfrey/jesus-you-are-real",
    },
    tags: ["Sample Rate", "WAV", "FLAC"],
    guests: [13],
    virtualLink: "https://x.com/i/spaces/1RJjppApPbNKw",
    listeners: 21,
    liveListeners: 17,
    series: "fc",
    meta: {
      src: "/uploads/logos/distrokid.jpg",
      title: 'Download & Listen to "Jesus You Are Real" by Jamiah Godfrey',
      url: "distrokid.com",
      cta: "Play Now",
    },
  },
  {
    id: 13,
    datetime: "2026-06-07T19:00:00.000Z",
    thumbnail: "/uploads/logos/thisday.png",
    topic: "ACID Traits for AI Workflows Pt.2",
    summary: "Keynotes from Onyebinamma Ebuka Peter's article by THISDAY",
    _notes: {
      headline:
        "From Writing Code to Designing Systems: How AI Is Redefining Software Engineering",
      url: "https://thisdaylive.com/2026/06/01/from-writing-code-to-designing-systems-how-ai-is-redefining-software-engineering",
    },
    tags: ["Prompting", "Architecture", "Judgement"],
    guests: [12],
    virtualLink: "https://x.com/i/spaces/1lKQRRgNYdyGE",
    listeners: 15,
    liveListeners: 12,
    series: "cs",
    meta: {
      src: "/uploads/logos/thisday.png",
      title:
        "From Writing Code to Designing Systems: How AI Is Redefining S...",
      url: "thisdaylive.com",
      cta: "Learn More",
    },
  },
  {
    id: 12,
    datetime: "2026-06-03T19:00:00.000Z",
    thumbnail: "/uploads/logos/snu-ri.jpg",
    topic: "ACID Traits for AI Workflows Pt.1",
    summary:
      "Keynotes from Madison Huang at Seoul National University (SNU) Robotics Institute",
    _notes: { yt: "https://youtu.be/dhMPSzedWNQ" },
    tags: ["Job Task", "Job Purpose", "AI FOMO"],
    virtualLink: "https://x.com/i/spaces/1dGYllLnveLKX",
    listeners: 3,
    liveListeners: 3,
    series: "cs",
    meta: {
      src: "/uploads/logos/snu-ri.jpg",
      title: "Madison Huang's Non-Linear Career | NVIDIA at SNU Robotics",
      url: "youtu.be/dhMPSzedWNQ",
      cta: "Watch Now",
    },
  },
  {
    id: 11,
    datetime: "2026-05-30T19:00:00.000Z",
    thumbnail: "/uploads/logos/ubth.png",
    topic: "Basic Routine Medical Investigations",
    tags: ["Urinalysis", "X-Ray", "ECG", "#Django"],
    guests: [11],
    notionUrl:
      "https://held-gambler-004.notion.site/Routine-Investigations-Modeling-36c6a7cc633c8017b911d6266fa82422",
    virtualLink: "https://x.com/i/spaces/1RKZzzBwanMKB",
    listeners: 66,
    liveListeners: 58,
    series: "fc",
  },
  {
    id: 10,
    datetime: "2026-05-28T19:00:00.000Z",
    thumbnail: "/uploads/logos/siiqo.png",
    topic: "Siiqo Design Session",
    tags: ["Marketplace", "Escrow", "Stablecoin"],
    guests: [9, 10],
    notionUrl:
      "https://held-gambler-004.notion.site/Siiqo-36c6a7cc633c8132842bf67ada4dd93d",
    virtualLink: "https://x.com/i/spaces/1qGvvvewvbkGB",
    listeners: 68,
    liveListeners: 42,
    meta: {
      src: "/uploads/logos/siiqo.png",
      title: "Escrow-based, Crypto-enabled, Digital Storefront for SMEs",
      url: "siiqo.com",
      cta: "Get Started",
    },
  },
  {
    id: 9,
    datetime: "2026-05-17T19:00:00.000Z",
    thumbnail: "/uploads/logos/moniepoint.png",
    topic: "KPIs of World-Class Software Engineers",
    summary: "Keynotes from Tosin Eniolorunda's speech at The Platform Nigeria",
    _notes: { yt: "https://youtu.be/OeP5Rs96OGY" },
    tags: ["Ownership", "Mentorship", "Scalability"],
    guests: [7, 8],
    notionUrl:
      "https://held-gambler-004.notion.site/KPIs-of-World-Class-Engineers-3486a7cc633c8078980ded890c2c9cc6",
    virtualLink: "https://x.com/i/spaces/1mGPaLAgERYJN",
    listeners: 24,
    liveListeners: 14,
    series: "cs",
  },
  {
    id: 7,
    datetime: "2026-04-12T19:00:00.000Z",
    thumbnail: "/uploads/logos/grab.png",
    topic: "Grab.com from MVP to Product Market Fit",
    summary: "Keynotes from Anthony Tan's interview by CNBC Int'l",
    _notes: { x: "@InsideGrab", yt: "https://youtu.be/PR2194ddosg" },
    notionUrl:
      "https://held-gambler-004.notion.site/Grab-com-from-MVP-to-PMF-3406a7cc633c817aba03ed635c6f6253",
    virtualLink: "https://x.com/i/spaces/1YxNrZNPNnpxw",
    listeners: 33,
    liveListeners: 10,
    series: "cs",
  },
  {
    id: 6,
    datetime: "2026-04-05T19:00:00.000Z",
    thumbnail: "/uploads/logos/adiz.png",
    topic: "Brand-Led Growth Hacking",
    summary:
      "Designing a brand identity that drive sales and customer loyalty.",
    guests: [6],
    notionUrl:
      "https://held-gambler-004.notion.site/Brand-Led-Growth-Hacking-3336a7cc633c810692e6e80f80946edb",
    virtualLink: "https://x.com/i/spaces/1rGmqojWqzqGy",
    listeners: 46,
    liveListeners: 31,
    series: "fc",
  },
  {
    id: 5,
    datetime: "2026-03-29T19:00:00.000Z",
    thumbnail: "/uploads/logos/tetra.png",
    topic: "Tetra Design Session",
    summary: "Virtual Dollar Cards for Seamless Int'l Transactions",
    guests: [5],
    notionUrl:
      "https://held-gambler-004.notion.site/Tetra-3316a7cc633c81429fabfb80a8601f8d",
    virtualLink: "https://x.com/i/spaces/1nxeLyZOkXLJX",
    listeners: 41,
    liveListeners: 21,
  },
  {
    id: 4,
    datetime: "2026-03-22T19:00:00.000Z",
    thumbnail: "/uploads/logos/izivote.png",
    topic: "Izivote Design Session",
    summary: "Cloud-based Voting Platform for Events & Campaigns",
    guests: [4],
    notionUrl:
      "https://held-gambler-004.notion.site/Izivote-3206a7cc633c807dbd55c6fbb373ff37",
    virtualLink: "https://x.com/i/spaces/1XGygmPjeMkxM",
    listeners: 93,
    liveListeners: 33,
  },
  {
    id: 3,
    datetime: "2026-03-15T19:00:00.000Z",
    thumbnail: "/uploads/logos/bookin.png",
    topic: "Bookin Design Session",
    summary: "All-in-one Booking Platform for Creative Professionals",
    guests: [3],
    notionUrl:
      "https://held-gambler-004.notion.site/Bookin-3226a7cc633c81f1a9d8ebbce7bbc6b3",
    virtualLink: "https://x.com/i/spaces/1DxleEjawjlKL",
    listeners: 136,
    liveListeners: 112,
  },
  {
    id: 2,
    datetime: "2026-03-08T19:00:00.000Z",
    thumbnail: "/uploads/logos/scupex.png",
    topic: "Scupex Design Session",
    summary: "Cloud-based, Multi-tenant School Management Solution",
    guests: [2],
    notionUrl:
      "https://held-gambler-004.notion.site/Scupex-31b6a7cc633c81eba6adcdddbe8fa5a1",
    virtualLink: "https://x.com/i/spaces/1qGvvkLwDBAGB",
    listeners: 139,
    liveListeners: 103,
  },
];
