import { EpisodeDto } from "./types";

export const data: EpisodeDto[] = [
  {
    id: 14,
    datetime: "2026-06-14T19:00:00.000Z",
    thumbnail: "/uploads/logos/distrokid.jpg",
    topic: "Gospel Music & Lossless Audio Compression",
    _notes: {
      url: "https://distrokid.com/hyperfollow/jamiahgodfrey/jesus-you-are-real",
    },
    tags: ["Distrokid", "Waveforms", "FLAC"],
    guests: [16],
    spaceUrl: "https://x.com/i/spaces/1aJbddZzqyaKX",
    listeners: 0,
    liveListeners: 0,
    series: "fc",
    meta: {
      src: "/uploads/logos/distrokid.jpg",
      title: `Download "Jesus You Are Real" by Jamiah Godfrey`,
      url: "distrokid.com",
      cta: "Play Now",
    },
  },
  {
    id: 13,
    datetime: "2026-06-07T19:00:00.000Z",
    thumbnail: "/uploads/logos/thisday.png",
    topic: "ACID Traits for AI Workflows Pt.2",
    summary: "Keynotes from Onyebinamma Ebuka Peter's article by THISDAY",
    _notes: {
      headline:
        "From Writing Code to Designing Systems: How AI Is Redefining Software Engineering",
      url: "https://thisdaylive.com/2026/06/01/from-writing-code-to-designing-systems-how-ai-is-redefining-software-engineering",
    },
    tags: ["Prompting", "Architecture", "Judgement"],
    guests: [15],
    spaceUrl: "https://x.com/i/spaces/1lKQRRgNYdyGE",
    listeners: 0,
    liveListeners: 0,
    series: "cs",
    meta: {
      src: "/uploads/logos/thisday.png",
      title: `From Writing Code to Designing Systems: How AI Is Redefining..`,
      url: "thisdaylive.com",
      cta: "Learn More",
    },
  },
  {
    id: 12,
    datetime: "2026-06-03T19:00:00.000Z",
    thumbnail: "/uploads/logos/snu-ri.jpg",
    topic: "ACID Traits for AI Workflows Pt.1",
    summary: "Keynotes from Madison Huang at Seoul National University Robotics Institute",
    _notes: { yt: "https://youtu.be/dhMPSzedWNQ" },
    tags: ["Job Task", "Job Purpose", "AI FOMO"],
    spaceUrl: "https://x.com/i/spaces/1dGYllLnveLKX",
    listeners: 0,
    liveListeners: 0,
    series: "cs",
    meta: {
      src: "/uploads/logos/snu-ri.jpg",
      title: "Madison Huang's Non-Linear Career | NVIDIA at SNU Robotics",
      url: "youtu.be/dhMPSzedWNQ",
      cta: "Watch Now",
    },
  },
  {
    id: 11,
    datetime: "2026-05-30T19:00:00.000Z",
    thumbnail: "/uploads/logos/ubth.png",
    topic: "Routine Medical Investigations_ API Modeling",
    tags: ["X-Ray", "ECG", "Urinalysis", "Django"],
    guests: [14],
    notionUrl:
      "https://held-gambler-004.notion.site/Routine-Investigations-Modeling-36c6a7cc633c8017b911d6266fa82422",
    spaceUrl: "https://x.com/i/spaces/1RKZzzBwanMKB",
    listeners: 66,
    liveListeners: 58,
    series: "fc",
  },
  {
    id: 10,
    datetime: "2026-05-28T19:00:00.000Z",
    thumbnail: "/uploads/logos/siiqo.png",
    topic: "Siiqo Design Session",
    tags: ["Marketplace", "Escrow", "Stablecoin",],
    guests: [12, 13],
    notionUrl:
      "https://held-gambler-004.notion.site/Siiqo-36c6a7cc633c8132842bf67ada4dd93d",
    spaceUrl: "https://x.com/i/spaces/1qGvvvewvbkGB",
    listeners: 67,
    liveListeners: 42,
    meta: {
      src: "/uploads/logos/siiqo.png",
      title: "Escrow-based, Crypto-enabled, Digital Storefront for SMEs",
      url: "siiqo.com",
      cta: "Get Started",
    },
  },
  {
    id: 9,
    datetime: "2026-05-17T19:00:00.000Z",
    thumbnail: "/uploads/logos/moniepoint.png",
    topic: "KPIs of World-Class Software Engineers",
    summary: "Keynotes from Tosin Eniolorunda's speech at The Platform Nigeria",
    _notes: { yt: "https://youtu.be/OeP5Rs96OGY" },
    tags: ["Ownership", "Mentorship", "Scalability"],
    guests: [11, 10],
    notionUrl:
      "https://held-gambler-004.notion.site/KPIs-of-World-Class-Engineers-3486a7cc633c8078980ded890c2c9cc6",
    spaceUrl: "https://x.com/i/spaces/1mGPaLAgERYJN",
    listeners: 24,
    liveListeners: 14,
    series: "cs",
  },
  {
    id: 8,
    datetime: "2026-04-18T19:00:00.000Z",
    thumbnail: "/uploads/logos/verse.png",
    topic: "Hype To Adoption: Building Web3 Products",
    summary: "Hosted by Verse Radio",
    _notes: { x: "@realVerseRadio" },
    guests: [9, 8, 7],
    displayAvatars: [
      "/images/icon-hwp.png",
      "/uploads/logos/btc.png",
      "/uploads/logos/verse.png",
    ],
    spaceUrl: "#https://x.com/i/spaces/1yxBeMlXgZPJN",
    listeners: 243,
    liveListeners: 243,
    series: "fc",
  },
  {
    id: 7,
    datetime: "2026-04-12T19:00:00.000Z",
    thumbnail: "/uploads/logos/grab.png",
    topic: "Grab.com from MVP to Product Market Fit",
    summary: "Keynotes from Anthony Tan's interview by CNBC Int'l",
    _notes: { x: "@InsideGrab", yt: "https://youtu.be/PR2194ddosg" },
    notionUrl:
      "https://held-gambler-004.notion.site/Grab-com-from-MVP-to-PMF-3406a7cc633c817aba03ed635c6f6253",
    spaceUrl: "https://x.com/i/spaces/1YxNrZNPNnpxw",
    listeners: 33,
    liveListeners: 10,
    series: "cs",
  },
  {
    id: 6,
    datetime: "2026-04-05T19:00:00.000Z",
    thumbnail: "/uploads/logos/adiz.png",
    topic: "Brand-Led Growth Hacking",
    summary:
      "Designing a brand identity that drive sales and customer loyalty.",
    guests: [6],
    notionUrl:
      "https://held-gambler-004.notion.site/Brand-Led-Growth-Hacking-3336a7cc633c810692e6e80f80946edb",
    spaceUrl: "https://x.com/i/spaces/1rGmqojWqzqGy",
    listeners: 45,
    liveListeners: 31,
    series: "fc",
  },
  {
    id: 5,
    datetime: "2026-03-29T19:00:00.000Z",
    thumbnail: "/uploads/logos/tetra.png",
    topic: "Tetra Design Session",
    summary: "Virtual Dollar Cards for Seamless Int'l Transactions",
    guests: [5],
    notionUrl:
      "https://held-gambler-004.notion.site/Tetra-3316a7cc633c81429fabfb80a8601f8d",
    spaceUrl: "https://x.com/i/spaces/1nxeLyZOkXLJX",
    listeners: 41,
    liveListeners: 21,
  },
  {
    id: 4,
    datetime: "2026-03-22T19:00:00.000Z",
    thumbnail: "/uploads/logos/izivote.png",
    topic: "Izivote Design Session",
    summary: "Cloud-based Voting Platform for Events & Campaigns",
    guests: [4],
    notionUrl:
      "https://held-gambler-004.notion.site/Izivote-3206a7cc633c807dbd55c6fbb373ff37",
    spaceUrl: "https://x.com/i/spaces/1XGygmPjeMkxM",
    listeners: 92,
    liveListeners: 33,
  },
  {
    id: 3,
    datetime: "2026-03-15T19:00:00.000Z",
    thumbnail: "/uploads/logos/bookin.png",
    topic: "Bookin Design Session",
    summary: "All-in-one Booking Platform for Creative Professionals",
    guests: [3],
    notionUrl:
      "https://held-gambler-004.notion.site/Bookin-3226a7cc633c81f1a9d8ebbce7bbc6b3",
    spaceUrl: "https://x.com/i/spaces/1DxleEjawjlKL",
    listeners: 136,
    liveListeners: 112,
  },
  {
    id: 2,
    datetime: "2026-03-08T19:00:00.000Z",
    thumbnail: "/uploads/logos/scupex.png",
    topic: "Scupex Design Session",
    summary: "Cloud-based, Multi-tenant School Management Solution",
    guests: [2],
    notionUrl:
      "https://held-gambler-004.notion.site/Scupex-31b6a7cc633c81eba6adcdddbe8fa5a1",
    spaceUrl: "https://x.com/i/spaces/1qGvvkLwDBAGB",
    listeners: 139,
    liveListeners: 103,
  },
  {
    id: 1,
    datetime: "2026-03-01T19:00:00.000Z",
    topic: "Northstar Design Session",
    summary: "AI-native, Cross-platform Product Analytics Solution",
    notionUrl:
      "https://held-gambler-004.notion.site/Northwind-AI-31b6a7cc633c8075b78ef30bf30c7ec7",
    spaceUrl: "#https://x.com/i/spaces/1nxnRYRXOgjxO",
    listeners: 31,
    liveListeners: 18,
  },
];
